server:
  port: 8080
  servlet:
    context-path: /ktjlpt
spring:
  application:
    name: ktjlpt

  datasource:
    url: jdbc:postgresql://localhost:5432/jlpt?TimeZone=Asia/Ho_Chi_Minh
    username: admin
    password: kaito2004
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000
  jwt:
    signerKey: "jzzMoshSc+dhmxTHzpZ1+T+DH3SfPO7idcJ6JrlsIjZgB6zI8N2PvJr6g3XjiQIIbt60Tkq4Fi56K4LBnTuYkg=="
    # 15 minutes
    access-exp: 900
    # 7 days
    refresh-exp: 604800

