server:
  port: 8080
  servlet:
    context-path: /ktjlpt
spring:
  application:
    name: ktjlpt

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000

  outbound:
    identity:
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}
      redirect_uri: "http://localhost:3000/authenticate"
      grant_type: "authorization_code"

  jwt:
    signerKey: ${JWT_SIGNER_KEY}
    # 15 minutes
    access-exp: 900
    # 7 days
    refresh-exp: 604800

